-- Create raw_trends table
CREATE TABLE IF NOT EXISTS raw_trends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trend_name TEXT NOT NULL,
  views_count TEXT,
  source TEXT DEFAULT 'TikTok',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create generated_posts table
CREATE TABLE IF NOT EXISTS generated_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trend TEXT,
  product TEXT,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_raw_trends_created_at ON raw_trends(created_at);
CREATE INDEX IF NOT EXISTS idx_generated_posts_status ON generated_posts(status);
